-- ============================================================
-- Script para crear nueva base de datos: plprint
-- La base de datos 'elovni' se mantiene intacta
-- ============================================================
-- EJECUTADO: Base de datos 'plprint' creada exitosamente
-- con 12 tablas (categorias, clientes, inventario, etc.)
-- ============================================================

-- Si necesitas recrear la base de datos desde cero:
--    mysql -u root -p < BDD.sql
--
-- Opcional: copiar datos de elovni a plprint (si se requiere):
--    mysqldump -u root -p --no-create-info elovni > datos_elovni.sql
--    mysql -u root -p plprint < datos_elovni.sql
